name: gayrimenkul_app
description: Gayrimenkul değerleme uygulaması

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  docx_template: ^0.4.3
  share_plus: ^12.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/template.docx
    - assets/gayrimenkul_degerleme.db
