name: gayrimenkul_app
description: Gayrimenkul değerleme uygulaması

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  # docx_template paketinde bazen build sorunları oluyor, daha stabil sürüm kullanalım
  docx_template: ^0.4.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/template.docx
    - assets/gayrimenkul_degerleme.db
